// Generated by gencpp from file test_srv/AddInts.msg
// DO NOT EDIT!


#ifndef TEST_SRV_MESSAGE_ADDINTS_H
#define TEST_SRV_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <test_srv/AddIntsRequest.h>
#include <test_srv/AddIntsResponse.h>


namespace test_srv
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace test_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_srv::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::test_srv::AddInts&) { return value(); }
};

template<>
struct DataType< ::test_srv::AddInts > {
  static const char* value()
  {
    return "test_srv/AddInts";
  }

  static const char* value(const ::test_srv::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::test_srv::AddIntsRequest> should match
// service_traits::MD5Sum< ::test_srv::AddInts >
template<>
struct MD5Sum< ::test_srv::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_srv::AddInts >::value();
  }
  static const char* value(const ::test_srv::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_srv::AddIntsRequest> should match
// service_traits::DataType< ::test_srv::AddInts >
template<>
struct DataType< ::test_srv::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::test_srv::AddInts >::value();
  }
  static const char* value(const ::test_srv::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_srv::AddIntsResponse> should match
// service_traits::MD5Sum< ::test_srv::AddInts >
template<>
struct MD5Sum< ::test_srv::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_srv::AddInts >::value();
  }
  static const char* value(const ::test_srv::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_srv::AddIntsResponse> should match
// service_traits::DataType< ::test_srv::AddInts >
template<>
struct DataType< ::test_srv::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::test_srv::AddInts >::value();
  }
  static const char* value(const ::test_srv::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_SRV_MESSAGE_ADDINTS_H
