// Generated by gencpp from file topic_test/add_int.msg
// DO NOT EDIT!


#ifndef TOPIC_TEST_MESSAGE_ADD_INT_H
#define TOPIC_TEST_MESSAGE_ADD_INT_H

#include <ros/service_traits.h>


#include <topic_test/add_intRequest.h>
#include <topic_test/add_intResponse.h>


namespace topic_test
{

struct add_int
{

typedef add_intRequest Request;
typedef add_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_int
} // namespace topic_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::topic_test::add_int > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::topic_test::add_int&) { return value(); }
};

template<>
struct DataType< ::topic_test::add_int > {
  static const char* value()
  {
    return "topic_test/add_int";
  }

  static const char* value(const ::topic_test::add_int&) { return value(); }
};


// service_traits::MD5Sum< ::topic_test::add_intRequest> should match
// service_traits::MD5Sum< ::topic_test::add_int >
template<>
struct MD5Sum< ::topic_test::add_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::topic_test::add_int >::value();
  }
  static const char* value(const ::topic_test::add_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_test::add_intRequest> should match
// service_traits::DataType< ::topic_test::add_int >
template<>
struct DataType< ::topic_test::add_intRequest>
{
  static const char* value()
  {
    return DataType< ::topic_test::add_int >::value();
  }
  static const char* value(const ::topic_test::add_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::topic_test::add_intResponse> should match
// service_traits::MD5Sum< ::topic_test::add_int >
template<>
struct MD5Sum< ::topic_test::add_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::topic_test::add_int >::value();
  }
  static const char* value(const ::topic_test::add_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::topic_test::add_intResponse> should match
// service_traits::DataType< ::topic_test::add_int >
template<>
struct DataType< ::topic_test::add_intResponse>
{
  static const char* value()
  {
    return DataType< ::topic_test::add_int >::value();
  }
  static const char* value(const ::topic_test::add_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TOPIC_TEST_MESSAGE_ADD_INT_H
